-- Web3Auth Migration Script
-- This script migrates from the old mnemonic-based wallet system to Web3Auth

-- Drop the old wallet table (no longer needed as Web3Auth manages keys)
DROP TABLE IF EXISTS public.wallet CASCADE;

-- Create new table for Web3Auth users
CREATE TABLE IF NOT EXISTS public.web3auth_users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
    web3auth_id text UNIQUE NOT NULL,
    wallet_address text NOT NULL,
    verifier text,
    verifier_id text,
    type_of_login text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT web3auth_users_wallet_address_check CHECK (wallet_address ~ '^0x[0-9a-fA-F]{40}$'::text)
);

-- Add wallet_address to profiles table (replacing derived_address and derived_public_key)
ALTER TABLE public.profiles
DROP COLUMN IF EXISTS derived_address,
DROP COLUMN IF EXISTS derived_public_key,
ADD COLUMN IF NOT EXISTS wallet_address text;

-- Add constraint for wallet address format
ALTER TABLE public.profiles
ADD CONSTRAINT profiles_wallet_address_check
CHECK (wallet_address IS NULL OR wallet_address ~ '^0x[0-9a-fA-F]{40}$'::text);

-- Update project_participants table to use wallet_address instead of derived addresses
ALTER TABLE public.project_participants
ADD COLUMN IF NOT EXISTS wallet_address text;

ALTER TABLE public.project_participants
ADD CONSTRAINT project_participants_wallet_address_check
CHECK (wallet_address IS NULL OR wallet_address ~ '^0x[0-9a-fA-F]{40}$'::text);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_web3auth_users_user_id ON public.web3auth_users(user_id);
CREATE INDEX IF NOT EXISTS idx_web3auth_users_wallet_address ON public.web3auth_users(wallet_address);
CREATE INDEX IF NOT EXISTS idx_web3auth_users_web3auth_id ON public.web3auth_users(web3auth_id);
CREATE INDEX IF NOT EXISTS idx_profiles_wallet_address ON public.profiles(wallet_address);
CREATE INDEX IF NOT EXISTS idx_project_participants_wallet_address ON public.project_participants(wallet_address);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_web3auth_users_updated_at
BEFORE UPDATE ON public.web3auth_users
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Grant necessary permissions (adjust based on your database user)
-- GRANT ALL PRIVILEGES ON public.web3auth_users TO your_app_user;
-- GRANT ALL PRIVILEGES ON public.web3auth_users_id_seq TO your_app_user;

-- Add comment for documentation
COMMENT ON TABLE public.web3auth_users IS 'Stores Web3Auth user authentication data and wallet addresses';
COMMENT ON COLUMN public.web3auth_users.web3auth_id IS 'Unique identifier from Web3Auth (verifierId or email)';
COMMENT ON COLUMN public.web3auth_users.wallet_address IS 'Ethereum wallet address generated by Web3Auth';
COMMENT ON COLUMN public.web3auth_users.verifier IS 'OAuth provider used for authentication';
COMMENT ON COLUMN public.web3auth_users.type_of_login IS 'Type of login method used (google, email, etc.)';

-- Migration complete message
DO $$
BEGIN
    RAISE NOTICE 'Web3Auth migration completed successfully';
    RAISE NOTICE 'Old wallet table has been dropped';
    RAISE NOTICE 'New web3auth_users table has been created';
    RAISE NOTICE 'Profiles and project_participants tables have been updated';
END $$;
