// path: src/services/image.service.js
import path from "path";
import fs from "fs";
import { pipeline } from "stream";
import { promisify } from "util";
import { v4 as uuidv4 } from "uuid";
import { fileURLToPath } from "url";
import Config from "#config";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const pump = promisify(pipeline);

// Legacy function - kept for backward compatibility but should be avoided
export const saveImage = async (data) => {
  console.warn('SECURITY WARNING: saveImage() is deprecated. Use saveSecureImage() instead.');
  try {
    // Définir le répertoire de destination
  const uploadsDir = path.join(__dirname, "../../uploads");

  // Créer le répertoire s'il n'existe pas
  if (!fs.existsSync(uploadsDir)) {
    fs.mkdirSync(uploadsDir, { recursive: true });
  }

  const filename = `${uuidv4()}-${data.filename}`;
  const savePath = path.join(uploadsDir, filename);
  await pump(data.file, fs.createWriteStream(savePath));

  console.log('=== savePath === images.service.js === key: 942641 ===');
  console.dir(savePath, { depth: null, colors: true })
  console.log('=================================');
  
  return filename;
  } catch (error) {
    console.log('=== error === images.service.js === key: 356356 ===');
    console.dir(error, { depth: null, colors: true })
    console.log('=================================');
    return {
      success: false,
      message: "Error saving image",
      errorKey: 597629,
      errorCode: "error-saving-image",
      fromError: Config.IN_PROD ? null : error.message,
    }
  }
};

/**
 * Secure image saving function that uses pre-validated file data
 * @param {Object} validatedFile - File data from validateImageUpload middleware
 */
export const saveSecureImage = async (validatedFile) => {
  try {
    // Définir le répertoire de destination
    const uploadsDir = path.join(__dirname, "../../uploads");

    // Créer le répertoire s'il n'existe pas
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }

    // Use the secure filename generated by the middleware
    const filename = validatedFile.secureFilename;
    const savePath = path.join(uploadsDir, filename);
    
    // Write the validated buffer to file
    await fs.promises.writeFile(savePath, validatedFile.buffer);

    console.log('=== Secure file saved === images.service.js === key: 942642 ===');
    console.log('Original filename:', validatedFile.originalFilename);
    console.log('Secure filename:', filename);
    console.log('File size:', validatedFile.size);
    console.log('MIME type:', validatedFile.mimetype);
    console.log('Save path:', savePath);
    console.log('=================================');
    
    return filename;
  } catch (error) {
    console.log('=== error === images.service.js === saveSecureImage === key: 356357 ===');
    console.dir(error, { depth: null, colors: true })
    console.log('=================================');
    return {
      success: false,
      message: "Error saving secure image",
      errorKey: 597630,
      errorCode: "error-saving-secure-image",
      fromError: Config.IN_PROD ? null : error.message,
    }
  }
};


